// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC9xtAdanOtJ3x66IKt6LtZb_jQgGti4o',
    appId: '1:420499107319:web:d1a3d2a3463296e5c952f2',
    messagingSenderId: '420499107319',
    projectId: 'cinema-afccf',
    authDomain: 'cinema-afccf.firebaseapp.com',
    storageBucket: 'cinema-afccf.appspot.com',
    measurementId: 'G-R482M59K30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsSYX78eDGKMTczWVy-q2iLUubc18CbP4',
    appId: '1:420499107319:android:b8e85cf80c69abc3c952f2',
    messagingSenderId: '420499107319',
    projectId: 'cinema-afccf',
    storageBucket: 'cinema-afccf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAENI-YGwy9v1Z1edBnJ-spG8jznQYGoGo',
    appId: '1:420499107319:ios:29bc214f080c555dc952f2',
    messagingSenderId: '420499107319',
    projectId: 'cinema-afccf',
    storageBucket: 'cinema-afccf.appspot.com',
    androidClientId: '420499107319-o0pa8575134a5lb6pa8lsn6e7mgtfbm4.apps.googleusercontent.com',
    iosClientId: '420499107319-bfdotuui6nhbcif2l131kv9353branee.apps.googleusercontent.com',
    iosBundleId: 'com.ducAn.cineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAENI-YGwy9v1Z1edBnJ-spG8jznQYGoGo',
    appId: '1:420499107319:ios:d490351443b27870c952f2',
    messagingSenderId: '420499107319',
    projectId: 'cinema-afccf',
    storageBucket: 'cinema-afccf.appspot.com',
    androidClientId: '420499107319-o0pa8575134a5lb6pa8lsn6e7mgtfbm4.apps.googleusercontent.com',
    iosClientId: '420499107319-i4dkvs8l8k00lrfidk1jlq4v4jrn8785.apps.googleusercontent.com',
    iosBundleId: 'com.example.cineApp.RunnerTests',
  );
}
